### ISSUE TITLE
`List index out of range` when the first chord of a song is written wrong

### ISSUE THREAD

**Issue by tonidb02** [bfrangi/pytransposer#1]
Steps to reproduce:

```python
>>> import pytransposer.transposer as tr
>>> tr.song_key('Some song\[Rem] with the first chord in wrong format\[MI]')
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bernat/.virtualenvs/songproject/lib/python3.10/site-packages/pytransposer/transposer.py", line 45, in song_key
    first_chord = config.get_chord_regex().findall(first_chord_group)[0]
IndexError: list index out of range
```

Problem is due to [line 45](https://github.com/bfrangi/pytransposer/blob/f5ef7edcbee9a7bffa2076bc14da1be14710c44d/src/pytransposer/transposer.py#L45):
```python
first_chord = config.get_chord_regex().findall(first_chord_group)[0]
```

**Comment by bfrangi** [comment]
Yes, we probably should handle that scenario more gracefully. I'll fix it as soon as possible. You're welcome to open a pull request if you feel up to it.
